os: linux
arch:
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install requests
script:
  python database-list.py
deploy:
  provider: pages
  local_dir: gh-pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
notifications:
  email:
    recipients:
      - joseph_anderson@fitnyc.edu
    on_success: never # default: change
    on_failure: always # default: always
